#include "ItemData.h"
#include <iostream>

using namespace std;

int weaponCount, armorCount, accessoryCount = 0;

weapon weaponList[200];
armor armorList[200];
accessory accessoryList[200];

void insertWeapon(weapon WEA, int totalWeapon){
    if(weaponCount < totalWeapon){
        weaponList[weaponCount++] = WEA;
    } else {
        cout << "Weapon Penuh" << endl;
    }
}

void insertArmor(armor ARM, int totalArmor){
    if(armorCount < totalArmor){
        armorList[armorCount++] = ARM;
    } else {
        cout << "Armor Penuh" << endl;
    }
}

void insertAccessory(accessory ACC, int totalAccessory){
    if(accessoryCount < totalAccessory){
        accessoryList[accessoryCount++] = ACC;
    } else {
        cout << "Accessory Penuh" << endl;
    }
}

void dataItem(){
    int totalWeapon = 100;
    int totalArmor = 100;
    int totalAccessory = 100;

    // Weapons
    insertWeapon({"Laevatein", 631}, totalWeapon);
    insertWeapon({"Excalibur", 544}, totalWeapon);
    insertWeapon({"Thunder Sword", 720}, totalWeapon);
    insertWeapon({"Flame Blade", 675}, totalWeapon);
    insertWeapon({"Shadow Dagger", 590}, totalWeapon);
    insertWeapon({"Ice Staff", 710}, totalWeapon);
    insertWeapon({"Phoenix Bow", 640}, totalWeapon);
    insertWeapon({"Crystal Halberd", 680}, totalWeapon);
    insertWeapon({"Dragon Slayer", 750}, totalWeapon);
    insertWeapon({"Sword of Destiny", 765}, totalWeapon);
    insertWeapon({"Divine Lance", 800}, totalWeapon);
    insertWeapon({"Venomous Dagger", 620}, totalWeapon);
    insertWeapon({"Lightning Spear", 670}, totalWeapon);
    insertWeapon({"Moonlit Blade", 750}, totalWeapon);
    insertWeapon({"Sunstrike Sword", 730}, totalWeapon);
    insertWeapon({"Valkyrie Bow", 680}, totalWeapon);
    insertWeapon({"Glacier Staff", 690}, totalWeapon);
    insertWeapon({"Inferno Sword", 780}, totalWeapon);
    insertWeapon({"Obsidian Edge", 740}, totalWeapon);
    insertWeapon({"Stormbreaker", 710}, totalWeapon);
    insertWeapon({"Titan Slayer", 800}, totalWeapon);
    insertWeapon({"Soul Reaver", 760}, totalWeapon);
    insertWeapon({"Warlord's Blade", 770}, totalWeapon);
    insertWeapon({"Demon's Fang", 750}, totalWeapon);
    insertWeapon({"Ice Fang", 720}, totalWeapon);
    insertWeapon({"Phoenix Flame", 730}, totalWeapon);
    insertWeapon({"Shadowstrike Dagger", 690}, totalWeapon);
    insertWeapon({"Frostbite Blade", 710}, totalWeapon);
    insertWeapon({"Warrior's Axe", 680}, totalWeapon);
    insertWeapon({"Dragon's Claw", 770}, totalWeapon);
    insertWeapon({"Ceremonial Sword", 720}, totalWeapon);
    insertWeapon({"Royal Spear", 740}, totalWeapon);
    insertWeapon({"Blackfire Sword", 750}, totalWeapon);
    insertWeapon({"Raging Blade", 760}, totalWeapon);
    insertWeapon({"Silver Bow", 730}, totalWeapon);
    insertWeapon({"Goldenshield Sword", 700}, totalWeapon);
    insertWeapon({"Chaos Blade", 720}, totalWeapon);
    insertWeapon({"Stormbreaker Sword", 770}, totalWeapon);
    insertWeapon({"Obsidian Dagger", 740}, totalWeapon);
    insertWeapon({"Venom Sword", 690}, totalWeapon);
    insertWeapon({"Lightbringer Sword", 740}, totalWeapon);
    insertWeapon({"Spectral Blade", 700}, totalWeapon);
    insertWeapon({"Doom Hammer", 730}, totalWeapon);
    insertWeapon({"Windweaver Sword", 680}, totalWeapon);
    insertWeapon({"Hallowed Sword", 750}, totalWeapon);
    insertWeapon({"Crystal Scepter", 710}, totalWeapon);
    insertWeapon({"Titan's Edge", 760}, totalWeapon);
    insertWeapon({"Silver Spear", 740}, totalWeapon);
    insertWeapon({"Firestorm Blade", 770}, totalWeapon);
    insertWeapon({"Berserker's Blade", 730}, totalWeapon);
    insertWeapon({"Reaper's Scythe", 760}, totalWeapon);
    insertWeapon({"Divine Sword", 740}, totalWeapon);
    insertWeapon({"Frostbrand Sword", 700}, totalWeapon);
    insertWeapon({"Hellfire Bow", 730}, totalWeapon);
    insertWeapon({"Thunderstrike Sword", 710}, totalWeapon);
    insertWeapon({"Ancient Sword", 740}, totalWeapon);
    insertWeapon({"Nightmare Blade", 760}, totalWeapon);
    insertWeapon({"Basilisk Fang", 710}, totalWeapon);
    insertWeapon({"Moonlit Dagger", 740}, totalWeapon);
    insertWeapon({"Vortex Sword", 750}, totalWeapon);
    insertWeapon({"Shadowblade", 730}, totalWeapon);
    insertWeapon({"Soulpiercer Sword", 760}, totalWeapon);
    insertWeapon({"Wrath of the Gods", 740}, totalWeapon);
    insertWeapon({"Searing Sword", 700}, totalWeapon);
    insertWeapon({"Stormcaller's Blade", 720}, totalWeapon);
    insertWeapon({"Hellrune Sword", 740}, totalWeapon);
    insertWeapon({"Darkfire Dagger", 710}, totalWeapon);
    insertWeapon({"Vengeful Blade", 730}, totalWeapon);
    insertWeapon({"Sunburst Bow", 760}, totalWeapon);
    insertWeapon({"Soulcaster Sword", 750}, totalWeapon);
    insertWeapon({"Phoenix Wing Sword", 740}, totalWeapon);
    insertWeapon({"Ravager's Axe", 700}, totalWeapon);
    insertWeapon({"Zephyr's Edge", 710}, totalWeapon);
    insertWeapon({"Elder's Sword", 730}, totalWeapon);
    insertWeapon({"Blazing Sword", 750}, totalWeapon);
    insertWeapon({"Dragonclaw Dagger", 760}, totalWeapon);
    insertWeapon({"Infernal Bow", 710}, totalWeapon);
    insertWeapon({"Gale Blade", 740}, totalWeapon);
    insertWeapon({"Dragonfang Dagger", 730}, totalWeapon);
    insertWeapon({"Dawnstrike Sword", 760}, totalWeapon);
    insertWeapon({"Crescent Blade", 740}, totalWeapon);
    insertWeapon({"Soulshard Sword", 720}, totalWeapon);
    insertWeapon({"Frozen Fang", 700}, totalWeapon);
    insertWeapon({"King's Edge", 740}, totalWeapon);
    insertWeapon({"Phantom Edge", 710}, totalWeapon);
    insertWeapon({"Nightfall Sword", 750}, totalWeapon);
    insertWeapon({"Lightwave Sword", 730}, totalWeapon);
    insertWeapon({"Warpath Dagger", 720}, totalWeapon);
    insertWeapon({"Frostshard Sword", 740}, totalWeapon);
    insertWeapon({"Stormstrike Sword", 730}, totalWeapon);
    insertWeapon({"Sword of Light", 800}, totalWeapon);
    insertWeapon({"Infernal Scythe", 740}, totalWeapon);
    insertWeapon({"Venomous Fang", 690}, totalWeapon);
    insertWeapon({"Thunderstrike Axe", 750}, totalWeapon);
    insertWeapon({"Eclipse Blade", 725}, totalWeapon);
    insertWeapon({"Dragon's Fury", 780}, totalWeapon);
    insertWeapon({"Stormcaller Staff", 710}, totalWeapon);
    insertWeapon({"Valkyrie's Spear", 765}, totalWeapon);
    insertWeapon({"Meteor Hammer", 700}, totalWeapon);
    insertWeapon({"Glacier Sword", 730}, totalWeapon);

    // Armors
    insertArmor({"Aquarius Imperial Armor", 250, 1606}, totalArmor);
    insertArmor({"Aries Bustier", 370, 1133}, totalArmor);
    insertArmor({"Knight Plate", 450, 1400}, totalArmor);
    insertArmor({"Golden Shield", 320, 1230}, totalArmor);
    insertArmor({"Steel Breastplate", 400, 1350}, totalArmor);
    insertArmor({"Shadow Cloak", 290, 1100}, totalArmor);
    insertArmor({"Mage Robe", 330, 1000}, totalArmor);
    insertArmor({"Celestial Armor", 500, 1800}, totalArmor);
    insertArmor({"Inferno Shield", 460, 1500}, totalArmor);
    insertArmor({"Guardian Armor", 480, 1400}, totalArmor);
    insertArmor({"Demonhide Armor", 370, 1300}, totalArmor);
    insertArmor({"Titan Plate", 500, 1600}, totalArmor);
    insertArmor({"Vampire Cloak", 300, 1250}, totalArmor);
    insertArmor({"Dragon Scale Armor", 450, 1400}, totalArmor);
    insertArmor({"Silver Guard", 400, 1200}, totalArmor);
    insertArmor({"Obsidian Chestplate", 430, 1350}, totalArmor);
    insertArmor({"Crimson Robe", 340, 1100}, totalArmor);
    insertArmor({"Steel Knight Armor", 420, 1450}, totalArmor);
    insertArmor({"Blacksmith's Armor", 380, 1300}, totalArmor);
    insertArmor({"Manticore Armor", 460, 1500}, totalArmor);
    insertArmor({"Paladin Plate", 490, 1600}, totalArmor);
    insertArmor({"Berserker Armor", 450, 1400}, totalArmor);
    insertArmor({"Assassin's Cloak", 320, 1150}, totalArmor);
    insertArmor({"Royal Guard Armor", 480, 1450}, totalArmor);
    insertArmor({"Moonlight Armor", 470, 1550}, totalArmor);
    insertArmor({"Phoenix Wings Armor", 500, 1700}, totalArmor);
    insertArmor({"Warlord Plate", 460, 1500}, totalArmor);
    insertArmor({"Lightcloak Armor", 330, 1200}, totalArmor);
    insertArmor({"Steel Lord Armor", 420, 1350}, totalArmor);
    insertArmor({"Emberstone Armor", 440, 1400}, totalArmor);
    insertArmor({"Sphinx Armor", 380, 1300}, totalArmor);
    insertArmor({"Battle Armor", 430, 1450}, totalArmor);
    insertArmor({"Iron Knight Plate", 480, 1600}, totalArmor);
    insertArmor({"Forest Guardian Armor", 460, 1500}, totalArmor);
    insertArmor({"King's Mantle", 470, 1550}, totalArmor);
    insertArmor({"Shadow Knight Armor", 490, 1600}, totalArmor);
    insertArmor({"Crimson Shield Armor", 430, 1400}, totalArmor);
    insertArmor({"Stormrunner Armor", 460, 1500}, totalArmor);
    insertArmor({"Dragonscale Chestplate", 470, 1550}, totalArmor);
    insertArmor({"Deathclaw Armor", 440, 1400}, totalArmor);
    insertArmor({"Titanium Plate", 550, 1700}, totalArmor);
    insertArmor({"Phoenix Armor", 600, 1800}, totalArmor);
    insertArmor({"Void Cloak", 420, 1300}, totalArmor);
    insertArmor({"Holy Guardian Armor", 650, 2000}, totalArmor);
    insertArmor({"Elder Dragon Scales", 500, 1500}, totalArmor);
    insertArmor({"Black Knight Armor", 580, 1600}, totalArmor);
    insertArmor({"Warrior's Helm", 390, 1200}, totalArmor);
    insertArmor({"Vanguard Breastplate", 620, 1800}, totalArmor);
    insertArmor({"Dragonfire Plate", 660, 1900}, totalArmor);
    insertArmor({"Silverleaf Robe", 450, 1350}, totalArmor);
    insertArmor({"Mystic Cloak", 470, 1400}, totalArmor);
    insertArmor({"Crimson Armor", 510, 1450}, totalArmor);
    insertArmor({"Storm Armor", 550, 1600}, totalArmor);
    insertArmor({"Shadow Knight Plate", 590, 1750}, totalArmor);
    insertArmor({"Sapphire Shield", 540, 1500}, totalArmor);
    insertArmor({"Steelheart Breastplate", 630, 1850}, totalArmor);
    insertArmor({"Cobalt Plate", 520, 1550}, totalArmor);
    insertArmor({"Frostguard Armor", 570, 1650}, totalArmor);
    insertArmor({"Lunar Robe", 460, 1400}, totalArmor);
    insertArmor({"Runeplate Armor", 600, 1700}, totalArmor);
    insertArmor({"Golden Plate", 650, 1850}, totalArmor);
    insertArmor({"Nightshade Cloak", 430, 1250}, totalArmor);
    insertArmor({"Dragonscale Breastplate", 640, 1750}, totalArmor);
    insertArmor({"Celestial Robe", 490, 1450}, totalArmor);
    insertArmor({"Emberforge Armor", 570, 1600}, totalArmor);
    insertArmor({"Ironclad Plate", 600, 1850}, totalArmor);
    insertArmor({"Deathshroud Cloak", 420, 1300}, totalArmor);
    insertArmor({"Runic Shield", 510, 1400}, totalArmor);
    insertArmor({"Spectral Armor", 480, 1500}, totalArmor);
    insertArmor({"Eternal Knight Armor", 550, 1600}, totalArmor);
    insertArmor({"Stormforged Plate", 620, 1700}, totalArmor);
    insertArmor({"Vampiric Robe", 440, 1350}, totalArmor);
    insertArmor({"Gilded Armor", 630, 1850}, totalArmor);
    insertArmor({"Frostbite Plate", 580, 1650}, totalArmor);
    insertArmor({"Soul Reaver Cloak", 460, 1400}, totalArmor);
    insertArmor({"Royal Guard Armor", 590, 1750}, totalArmor);
    insertArmor({"Thunderstrike Plate", 620, 1800}, totalArmor);
    insertArmor({"Molten Breastplate", 610, 1700}, totalArmor);
    insertArmor({"Gladiator's Armor", 550, 1600}, totalArmor);
    insertArmor({"Void Plate", 670, 1900}, totalArmor);
    insertArmor({"Titanium Cloak", 480, 1450}, totalArmor);
    insertArmor({"Phoenix Robe", 510, 1500}, totalArmor);
    insertArmor({"Silver Sentinel Armor", 600, 1750}, totalArmor);
    insertArmor({"Omen Cloak", 440, 1350}, totalArmor);
    insertArmor({"Obsidian Plate", 570, 1600}, totalArmor);
    insertArmor({"Crusader's Armor", 650, 1850}, totalArmor);
    insertArmor({"Shadowplate", 590, 1700}, totalArmor);
    insertArmor({"Dragonskin Cloak", 470, 1400}, totalArmor);
    insertArmor({"Fortified Armor", 600, 1800}, totalArmor);
    insertArmor({"Ironplate Vest", 510, 1450}, totalArmor);
    insertArmor({"Bloodstone Plate", 590, 1750}, totalArmor);
    insertArmor({"Arcane Robe", 530, 1550}, totalArmor);
    insertArmor({"Thunderplate", 640, 1850}, totalArmor);
    insertArmor({"Mystic Armor", 460, 1400}, totalArmor);
    insertArmor({"Ironclad Robe", 540, 1500}, totalArmor);
    insertArmor({"Titan Robe", 480, 1350}, totalArmor);
    insertArmor({"Vampire's Cloak", 520, 1450}, totalArmor);
    insertArmor({"Darkfire Armor", 570, 1600}, totalArmor);
    insertArmor({"Warlord's Breastplate", 610, 1700}, totalArmor);
    insertArmor({"Necrotic Cloak", 450, 1400}, totalArmor);
    insertArmor({"Eternal Plate", 590, 1750}, totalArmor);
    insertArmor({"Celestial Cloak", 530, 1500}, totalArmor);
    insertArmor({"Moonlit Armor", 560, 1600}, totalArmor);
    insertArmor({"Blacksteel Armor", 630, 1800}, totalArmor);
    insertArmor({"Azure Breastplate", 500, 1500}, totalArmor);
    insertArmor({"Dreadplate", 650, 1850}, totalArmor);
    insertArmor({"Shadowbane Armor", 600, 1700}, totalArmor);
    insertArmor({"Regal Armor", 650, 1900}, totalArmor);
    insertArmor({"Scorched Plate", 570, 1600}, totalArmor);
    insertArmor({"Grim Cloak", 490, 1450}, totalArmor);
    insertArmor({"Phoenix Guard Armor", 630, 1800}, totalArmor);
    insertArmor({"Stormfront Plate", 620, 1750}, totalArmor);
    insertArmor({"Corrupted Plate", 590, 1700}, totalArmor);
    insertArmor({"Starfire Cloak", 540, 1550}, totalArmor);
    insertArmor({"Frozen Plate", 600, 1800}, totalArmor);

    // Aksesori
    insertAccessory({"Euclase Earth", 188, 857, 300}, totalAccessory);
    insertAccessory({"Neptune Malachite", 44, 441, 500}, totalAccessory);
    insertAccessory({"Ring of Strength", 120, 400, 200}, totalAccessory);
    insertAccessory({"Amulet of Wisdom", 90, 600, 250}, totalAccessory);
    insertAccessory({"Bracelet of Speed", 140, 300, 300}, totalAccessory);
    insertAccessory({"Cloak of Shadows", 80, 700, 400}, totalAccessory);
    insertAccessory({"Necklace of Power", 200, 500, 350}, totalAccessory);
    insertAccessory({"Ring of Agility", 130, 450, 280}, totalAccessory);
    insertAccessory({"Charm of Resilience", 110, 550, 320}, totalAccessory);
    insertAccessory({"Talisman of Healing", 70, 400, 250}, totalAccessory);
    insertAccessory({"Amulet of Valor", 150, 550, 280}, totalAccessory);
    insertAccessory({"Pendant of Fortune", 90, 650, 220}, totalAccessory);
    insertAccessory({"Earring of Light", 160, 600, 310}, totalAccessory);
    insertAccessory({"Belt of Strength", 120, 400, 230}, totalAccessory);
    insertAccessory({"Ring of Fortune", 140, 450, 270}, totalAccessory);
    insertAccessory({"Boots of Speed", 130, 470, 250}, totalAccessory);
    insertAccessory({"Necklace of Vitality", 200, 550, 280}, totalAccessory);
    insertAccessory({"Crown of Wisdom", 80, 500, 310}, totalAccessory);
    insertAccessory({"Bracelet of Energy", 110, 520, 290}, totalAccessory);
    insertAccessory({"Moonstone Amulet", 140, 600, 220}, totalAccessory);
    insertAccessory({"Heart of Courage", 150, 480, 330}, totalAccessory);
    insertAccessory({"Ring of Fire", 180, 550, 350}, totalAccessory);
    insertAccessory({"Shield of Spirit", 90, 500, 280}, totalAccessory);
    insertAccessory({"Diamond Necklace", 130, 520, 300}, totalAccessory);
    insertAccessory({"Windfall Bracelet", 160, 470, 330}, totalAccessory);
    insertAccessory({"Frostbite Earring", 140, 600, 270}, totalAccessory);
    insertAccessory({"Serenity Charm", 120, 510, 250}, totalAccessory);
    insertAccessory({"Dawn Talisman", 110, 540, 260}, totalAccessory);
    insertAccessory({"Inferno Ring", 160, 590, 320}, totalAccessory);
    insertAccessory({"Shining Pendant", 180, 530, 340}, totalAccessory);
    insertAccessory({"Veil of Night", 150, 460, 300}, totalAccessory);
    insertAccessory({"Sunfire Charm", 130, 510, 330}, totalAccessory);
    insertAccessory({"Eclipse Band", 120, 520, 240}, totalAccessory);
    insertAccessory({"Aether Amulet", 170, 600, 330}, totalAccessory);
    insertAccessory({"Starfire Ring", 180, 480, 310}, totalAccessory);
    insertAccessory({"Emberstone Pendant", 130, 500, 250}, totalAccessory);
    insertAccessory({"Titan's Belt", 150, 540, 290}, totalAccessory);
    insertAccessory({"Frostglow Charm", 160, 520, 270}, totalAccessory);
    insertAccessory({"Stoneheart Necklace", 140, 550, 330}, totalAccessory);
    insertAccessory({"Radiance Cuffs", 150, 470, 310}, totalAccessory);
    insertAccessory({"Mystic Shield", 160, 530, 300}, totalAccessory);
    insertAccessory({"Bloodstone Ring", 140, 480, 320}, totalAccessory);
    insertAccessory({"Veil of Time", 170, 510, 330}, totalAccessory);
    insertAccessory({"Phoenix Talisman", 130, 490, 300}, totalAccessory);
    insertAccessory({"Elemental Bracelet", 180, 600, 350}, totalAccessory);
    insertAccessory({"Abyssal Earring", 150, 530, 280}, totalAccessory);
    insertAccessory({"Lunar Amulet", 110, 460, 270}, totalAccessory);
    insertAccessory({"Spiritstone Ring", 130, 500, 290}, totalAccessory);
    insertAccessory({"Talisman of Power", 160, 550, 310}, totalAccessory);
    insertAccessory({"Coral Charm", 120, 490, 270}, totalAccessory);
    insertAccessory({"Warrior's Emblem", 180, 540, 320}, totalAccessory);
    insertAccessory({"Moonlight Band", 150, 500, 300}, totalAccessory);
    insertAccessory({"Fury Gem", 140, 510, 260}, totalAccessory);
    insertAccessory({"Titan's Crest", 170, 550, 340}, totalAccessory);
    insertAccessory({"Warden's Ring", 120, 480, 250}, totalAccessory);
    insertAccessory({"Golden Tear Necklace", 180, 570, 320}, totalAccessory);
    insertAccessory({"Stormbound Cuffs", 130, 460, 290}, totalAccessory);
    insertAccessory({"Royal Sigil", 150, 500, 310}, totalAccessory);
    insertAccessory({"Soulfire Band", 170, 540, 330}, totalAccessory);
    insertAccessory({"Courageous Ring", 160, 480, 310}, totalAccessory);
    insertAccessory({"Embercrest Charm", 140, 520, 300}, totalAccessory);
    insertAccessory({"Eclipse Amulet", 150, 510, 320}, totalAccessory);
    insertAccessory({"Windshear Pendant", 180, 550, 330}, totalAccessory);
    insertAccessory({"Runestone Earring", 120, 480, 290}, totalAccessory);
    insertAccessory({"Guardian's Token", 160, 520, 320}, totalAccessory);
    insertAccessory({"Sapphire Ring", 140, 540, 270}, totalAccessory);
    insertAccessory({"Frozen Band", 130, 510, 280}, totalAccessory);
    insertAccessory({"Astral Talisman", 150, 500, 310}, totalAccessory);
    insertAccessory({"Pyrostone Amulet", 140, 530, 320}, totalAccessory);
    insertAccessory({"Tempest Charm", 120, 490, 270}, totalAccessory);
    insertAccessory({"Mystic Crown", 150, 540, 290}, totalAccessory);
    insertAccessory({"Dragonstone Pendant", 130, 460, 260}, totalAccessory);
    insertAccessory({"Windwalker Ring", 180, 570, 310}, totalAccessory);
    insertAccessory({"Stormcaller Charm", 140, 500, 300}, totalAccessory);
    insertAccessory({"Shadowmoon Band", 160, 530, 270}, totalAccessory);
    insertAccessory({"Thunderbolt Necklace", 170, 550, 310}, totalAccessory);
    insertAccessory({"Diamond Band", 130, 480, 260}, totalAccessory);
    insertAccessory({"Crescent Amulet", 150, 510, 280}, totalAccessory);
    insertAccessory({"Abyssal Ring", 180, 540, 330}, totalAccessory);
    insertAccessory({"Emerald Charm", 140, 520, 290}, totalAccessory);
    insertAccessory({"Solar Amulet", 160, 550, 300}, totalAccessory);
    insertAccessory({"Infernal Pendant", 120, 470, 250}, totalAccessory);
    insertAccessory({"Ruby Band", 150, 510, 320}, totalAccessory);
    insertAccessory({"Lunar Pendant", 180, 540, 300}, totalAccessory);
    insertAccessory({"Iceheart Necklace", 130, 480, 280}, totalAccessory);
    insertAccessory({"Shadowcloak Charm", 140, 510, 270}, totalAccessory);
    insertAccessory({"Stormcaller Band", 160, 530, 310}, totalAccessory);
    insertAccessory({"Celestial Amulet", 180, 550, 320}, totalAccessory);
    insertAccessory({"Thunderstrike Pendant", 130, 490, 290}, totalAccessory);
    insertAccessory({"Firestone Ring", 150, 520, 300}, totalAccessory);
    insertAccessory({"Frostveil Necklace", 170, 530, 330}, totalAccessory);
    insertAccessory({"Obsidian Talisman", 120, 480, 280}, totalAccessory);
    insertAccessory({"Heaven's Embrace", 180, 540, 310}, totalAccessory);
    insertAccessory({"Elderstone Ring", 130, 500, 320}, totalAccessory);
    insertAccessory({"Astral Band", 150, 520, 270}, totalAccessory);
    insertAccessory({"Flameheart Necklace", 170, 540, 300}, totalAccessory);
    insertAccessory({"Starlight Pendant", 120, 490, 260}, totalAccessory);
    insertAccessory({"Ring of Power", 50, 0, 200}, totalAccessory);
    insertAccessory({"Amulet of Life", 0, 300, 0}, totalAccessory);
    insertAccessory({"Boots of Speed", 30, 0, 100}, totalAccessory);

}

